#!/bin/bash
# Sync every service from catalog.jacob.st into Homelab/Services/<name>.md
# in the Obsidian vault.
#
# - GET catalog → for each service, build YAML frontmatter
# - GET obsidian file: 404 → create with frontmatter + stub body
#                       200 → split on second `---`, replace top half (preserve body)
# - PUT back only if frontmatter actually changed
#
# Schedule: every 4 hours
# Secrets via wm-secret (Infisical):
#   THESYS_CF_ACCESS, CATALOG_API_KEY, OBSIDIAN_API_KEY
set -euo pipefail

CF_ID="c041e85854a69aa2581c105f5cf11d93.access"   # thesys-wallos service token client_id
CF_SECRET="$(wm-secret THESYS_CF_ACCESS)"
CATALOG_KEY="$(wm-secret CATALOG_API_KEY)"
OBSIDIAN_KEY="$(wm-secret OBSIDIAN_API_KEY)"

CATALOG=https://catalog.jacob.st
OBSIDIAN=https://obsidian.jacob.st
ICONS=https://icons.jacob.st
FOLDER="Homelab/Services"
SECRETS_FOLDER="Homelab/Secrets"
ICON_FOLDER=".obsidian/icons/self-host"
ICON_PREFIX="Sh"                       # Iconize custom-pack prefix
FORCE="${FORCE:-false}"                # set FORCE=true to re-PUT every note regardless of diff

# ── helpers ────────────────────────────────────────────────────────

cf_curl() {
  curl -s \
    -H "CF-Access-Client-Id: $CF_ID" \
    -H "CF-Access-Client-Secret: $CF_SECRET" \
    "$@"
}

# Build YAML frontmatter. $2 is the optional Iconize reference (e.g. "ShFileBrowser").
build_frontmatter() {
  local svc="$1"
  local iconize="${2:-}"
  jq -r --arg iconize "$iconize" '
    def yamlVal(v):
      if v == null then "null"
      elif (v|type) == "string" then v
      elif (v|type) == "number" or (v|type) == "boolean" then v|tostring
      else v|tojson end;
    def yamlList(arr):
      if (arr|length) == 0 then " []"
      else "\n" + (arr | map("  - " + (yamlVal(.))) | join("\n")) end;

    "---",
    "# auto-generated by windmill: sync-catalog-to-obsidian — do not edit by hand",
    "# edits below the second `---` are preserved",
    "name: " + (.name // ""),
    "category: " + (.category // ""),
    "host: " + (.host // ""),
    "status: " + (.status // ""),
    "description: " + ((.description // "") | tojson),
    "icon: " + $iconize,
    "icon_url: " + (.icon_url // ""),
    "url: " + (if (.hostnames|length) > 0 then "https://" + .hostnames[0] else "" end),
    "urls:" + yamlList((.hostnames // []) | map("https://" + .)),
    "ports:" + yamlList(.ports // []),
    "containers:" + yamlList(.containers // []),
    "infisical_secrets:" + yamlList(.infisical_secrets // []),
    "tags:" + yamlList(.tags // []),
    "docs_url: " + (.docs_url // ""),
    "internal: " + ((.internal // false)|tostring),
    "catalog_link: \"https://catalog.jacob.st/api/services/" + .name + "\"",
    "last_synced: \"" + (now | strftime("%Y-%m-%dT%H:%M:%SZ")) + "\"",
    "---"
  ' <<< "$svc"
}

# Build stub body for new files.
build_stub_body() {
  local svc="$1"
  local name desc
  name=$(jq -r '.name' <<< "$svc")
  desc=$(jq -r '.description // ""' <<< "$svc")
  printf '\n# %s\n\n%s\n\n## Notes\n\n' "$name" "$desc"
}

# Encode a path segment for URL.
urlenc() { jq -rn --arg s "$1" '$s|@uri'; }

# kebab-case → PascalCase: "file-browser" → "FileBrowser"
pascal_case() {
  echo "$1" | awk -F'-' '{out=""; for(i=1;i<=NF;i++) out = out toupper(substr($i,1,1)) substr($i,2); print out}'
}

# Cache of icon names already ensured this run, value="" if fetch failed.
declare -A ICON_CACHE

# Ensure the SVG for a given icon_url is in the vault. Echoes the
# Iconize reference name (e.g. "ShFileBrowser") on success, or empty
# string on failure. Empty when icon_url is empty/upstream is 404.
ensure_icon() {
  local icon_url="$1"
  [ -z "$icon_url" ] && { echo ""; return; }
  if [ -n "${ICON_CACHE[$icon_url]+x}" ]; then
    echo "${ICON_CACHE[$icon_url]}"
    return
  fi
  local raw_name pascal vault_path code
  raw_name=$(basename "$icon_url" .svg)
  pascal=$(pascal_case "$raw_name")
  vault_path="$ICON_FOLDER/$pascal.svg"

  # Already in vault? skip the upstream fetch.
  code=$(cf_curl -H "X-API-Key: $OBSIDIAN_KEY" \
    -o /dev/null -w "%{http_code}" \
    "$OBSIDIAN/api/files/$(urlenc "$vault_path")")
  if [ "$code" = "200" ]; then
    ICON_CACHE[$icon_url]="$pascal"
    echo "$pascal"
    return
  fi

  # Fetch upstream SVG (icons.jacob.st is unauthenticated)
  local svg http
  http=$(curl -s -w "%{http_code}" -o /tmp/_icon.svg "$icon_url")
  if [ "$http" != "200" ]; then
    ICON_CACHE[$icon_url]=""
    echo ""
    return
  fi
  svg=$(cat /tmp/_icon.svg)
  rm -f /tmp/_icon.svg

  # PUT into vault
  local payload
  payload=$(jq -n --arg c "$svg" '{content: $c}')
  local put_code
  put_code=$(cf_curl -X PUT -H "X-API-Key: $OBSIDIAN_KEY" -H "Content-Type: application/json" \
    -d "$payload" -o /dev/null -w "%{http_code}" \
    "$OBSIDIAN/api/files/$(urlenc "$vault_path")")
  if [ "$put_code" = "201" ] || [ "$put_code" = "200" ]; then
    ICON_CACHE[$icon_url]="$pascal"
    echo "$pascal"
  else
    ICON_CACHE[$icon_url]=""
    echo ""
  fi
}

# ── main ───────────────────────────────────────────────────────────

echo "fetching catalog…"
SERVICES_JSON=$(cf_curl -H "X-API-Key: $CATALOG_KEY" "$CATALOG/api/services?internal=true")
TOTAL=$(jq '.count' <<< "$SERVICES_JSON")
echo "got $TOTAL services"

CREATED=0; UPDATED=0; UNCHANGED=0; ERRORS=0

# Iterate service names
NAMES=$(jq -r '.services[].name' <<< "$SERVICES_JSON")
for name in $NAMES; do
  svc=$(jq -c --arg n "$name" '.services[] | select(.name == $n)' <<< "$SERVICES_JSON")

  # Ensure the icon SVG is in the vault and get its Iconize reference name.
  # Empty string if no icon_url or upstream 404 — then `icon:` field will be empty.
  icon_url=$(jq -r '.icon_url // ""' <<< "$svc")
  pascal=$(ensure_icon "$icon_url")
  iconize=""
  [ -n "$pascal" ] && iconize="${ICON_PREFIX}${pascal}"

  newFM=$(build_frontmatter "$svc" "$iconize")
  filePath="$FOLDER/$name.md"
  encPath=$(urlenc "$filePath")

  # Try to read existing
  RESP=$(cf_curl -H "X-API-Key: $OBSIDIAN_KEY" -w "\n__HTTP__:%{http_code}" "$OBSIDIAN/api/files/$encPath")
  CODE=$(grep -oE '__HTTP__:[0-9]+$' <<< "$RESP" | cut -d: -f2)
  BODY=$(sed 's/__HTTP__:[0-9]*$//' <<< "$RESP")

  if [ "$CODE" = "200" ]; then
    # File exists — split on second `---`, keep the body
    EXISTING=$(jq -r '.content' <<< "$BODY")
    # Find the position after the second `---\n`. Use awk to track delimiter count.
    USER_BODY=$(awk 'BEGIN{c=0} /^---$/{c++; if(c==2){found=1; next}} found{print}' <<< "$EXISTING")
    NEW_FILE=$(printf '%s%s' "$newFM" "$(printf '\n%s' "$USER_BODY")")

    # Compare frontmatter only (strip dynamic last_synced for hash).
    norm_old=$(awk 'BEGIN{c=0; out=""} /^---$/{c++; if(c==2){print out; exit}} {if(!/^last_synced:/) out=out"\n"$0}' <<< "$EXISTING")
    norm_new=$(awk 'BEGIN{c=0; out=""} /^---$/{c++; if(c==2){print out; exit}} {if(!/^last_synced:/) out=out"\n"$0}' <<< "$newFM")

    if [ "$norm_old" = "$norm_new" ] && [ "$FORCE" != "true" ]; then
      UNCHANGED=$((UNCHANGED+1))
      continue
    fi

    PAYLOAD=$(jq -n --arg c "$NEW_FILE" '{content: $c}')
    R=$(cf_curl -X PUT -H "X-API-Key: $OBSIDIAN_KEY" -H "Content-Type: application/json" \
      -d "$PAYLOAD" -w "%{http_code}" -o /dev/null "$OBSIDIAN/api/files/$encPath")
    if [ "$R" = "201" ] || [ "$R" = "200" ]; then
      UPDATED=$((UPDATED+1))
    else
      echo "ERROR updating $name: HTTP $R"
      ERRORS=$((ERRORS+1))
    fi

  elif [ "$CODE" = "404" ]; then
    # New file — write frontmatter + stub body
    STUB=$(build_stub_body "$svc")
    NEW_FILE="${newFM}${STUB}"
    PAYLOAD=$(jq -n --arg c "$NEW_FILE" '{content: $c}')
    R=$(cf_curl -X PUT -H "X-API-Key: $OBSIDIAN_KEY" -H "Content-Type: application/json" \
      -d "$PAYLOAD" -w "%{http_code}" -o /dev/null "$OBSIDIAN/api/files/$encPath")
    if [ "$R" = "201" ]; then
      CREATED=$((CREATED+1))
    else
      echo "ERROR creating $name: HTTP $R"
      ERRORS=$((ERRORS+1))
    fi
  else
    echo "ERROR reading $name: HTTP $CODE"
    ERRORS=$((ERRORS+1))
  fi
done

echo ""
echo "summary: created=$CREATED updated=$UPDATED unchanged=$UNCHANGED errors=$ERRORS total=$TOTAL"

# ── Secrets cross-reference ────────────────────────────────────────
# Derive "Infisical key → which services consume it" from the catalog data.
# Writes Homelab/Secrets/README.md.
SECRETS_DOC=$(jq -r '
  # Flatten services → [{key, service}]
  [.services[]
    | {name, secrets: (.infisical_secrets // [])}
    | .name as $n
    | .secrets[]
    | {key: ., service: $n}]
  | group_by(.key)
  | map({key: .[0].key, services: [.[].service] | sort | unique})
  | sort_by(.key)
  | .
' <<< "$SERVICES_JSON")

SECRET_COUNT=$(jq 'length' <<< "$SECRETS_DOC")
SECRETS_MD="# Secrets cross-reference

**Auto-generated** by the catalog-sync process. Do not edit by hand.

Maps each Infisical key name to the service(s) that consume it. **Values live only in Infisical** at \`https://secrets.jacob.st\` — this file has key names only.

Last generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
Total keys referenced: $SECRET_COUNT

## Key → services

| Infisical key | Consumed by |
|---|---|
"
# Append one row per key
while read -r row; do
  key=$(jq -r '.key' <<< "$row")
  svcs=$(jq -r '.services | map("[[Services/" + . + "]]") | join(", ")' <<< "$row")
  SECRETS_MD="${SECRETS_MD}| \`$key\` | $svcs |
"
done < <(jq -c '.[]' <<< "$SECRETS_DOC")

SECRETS_MD="$SECRETS_MD
## How this is generated

Derived from each service's \`catalog.yml\` \`infisical_secrets:\` field (declared by the service owner) and surfaced by \`catalog.jacob.st/api/services/*.infisical_secrets\`. The sync process aggregates them here on every run.

## How to update

Edit the \`infisical_secrets:\` list in the relevant \`catalog.yml\` (under \`/root/docker-services/<service>/\` on resolution, or \`adventure\`). Push to the matching gitea repo. Within ~5 min the catalog re-reads; within 4h (or on manual sync) this file regenerates.

Missing a secret? The service's \`catalog.yml\` probably just doesn't declare it yet.
"

SECRETS_PAYLOAD=$(jq -n --arg c "$SECRETS_MD" '{content: $c}')
SECRETS_PATH="$SECRETS_FOLDER/README.md"
SECRETS_ENC=$(urlenc "$SECRETS_PATH")
SECRETS_RESP=$(cf_curl -X PUT -H "X-API-Key: $OBSIDIAN_KEY" -H "Content-Type: application/json" \
  -d "$SECRETS_PAYLOAD" -w "%{http_code}" -o /dev/null "$OBSIDIAN/api/files/$SECRETS_ENC")
echo "secrets: $SECRETS_PATH → HTTP $SECRETS_RESP ($SECRET_COUNT keys)"
