#!/bin/bash
# Sync every service from catalog.jacob.st into Homelab/Services/<name>.md
# in the Obsidian vault.
#
# - GET catalog → for each service, build YAML frontmatter
# - GET obsidian file: 404 → create with frontmatter + stub body
#                       200 → split on second `---`, replace top half (preserve body)
# - PUT back only if frontmatter actually changed
#
# Schedule: every 4 hours
# Secrets via wm-secret (Infisical):
#   THESYS_CF_ACCESS, CATALOG_API_KEY, OBSIDIAN_API_KEY
set -euo pipefail

CF_ID="c041e85854a69aa2581c105f5cf11d93.access"   # thesys-wallos service token client_id
CF_SECRET="$(wm-secret THESYS_CF_ACCESS)"
CATALOG_KEY="$(wm-secret CATALOG_API_KEY)"
OBSIDIAN_KEY="$(wm-secret OBSIDIAN_API_KEY)"

CATALOG=https://catalog.jacob.st
OBSIDIAN=https://obsidian.jacob.st
FOLDER="Homelab/Services"

# ── helpers ────────────────────────────────────────────────────────

cf_curl() {
  curl -s \
    -H "CF-Access-Client-Id: $CF_ID" \
    -H "CF-Access-Client-Secret: $CF_SECRET" \
    "$@"
}

# Build YAML frontmatter for one service record (jq -c → multi-line YAML).
build_frontmatter() {
  local svc="$1"
  jq -r '
    def yamlVal(v):
      if v == null then "null"
      elif (v|type) == "string" then v
      elif (v|type) == "number" or (v|type) == "boolean" then v|tostring
      else v|tojson end;
    def yamlList(arr):
      if (arr|length) == 0 then "[]"
      else "\n" + (arr | map("  - " + (yamlVal(.))) | join("\n")) end;

    "---",
    "# auto-generated by windmill: sync-catalog-to-obsidian — do not edit by hand",
    "# edits below the second `---` are preserved",
    "name: " + (.name // ""),
    "category: " + (.category // ""),
    "host: " + (.host // ""),
    "status: " + (.status // ""),
    "description: " + ((.description // "") | tojson),
    "icon_url: " + (.icon_url // ""),
    "hostnames:" + yamlList(.hostnames // []),
    "ports:" + yamlList(.ports // []),
    "containers:" + yamlList(.containers // []),
    "infisical_secrets:" + yamlList(.infisical_secrets // []),
    "tags:" + yamlList(.tags // []),
    "docs_url: " + (.docs_url // ""),
    "internal: " + ((.internal // false)|tostring),
    "catalog_link: \"https://catalog.jacob.st/api/services/" + .name + "\"",
    "last_synced: \"" + (now | strftime("%Y-%m-%dT%H:%M:%SZ")) + "\"",
    "---"
  ' <<< "$svc"
}

# Build stub body for new files.
build_stub_body() {
  local svc="$1"
  local name desc
  name=$(jq -r '.name' <<< "$svc")
  desc=$(jq -r '.description // ""' <<< "$svc")
  printf '\n# %s\n\n%s\n\n## Notes\n\n' "$name" "$desc"
}

# Encode a path segment for URL.
urlenc() { jq -rn --arg s "$1" '$s|@uri'; }

# ── main ───────────────────────────────────────────────────────────

echo "fetching catalog…"
SERVICES_JSON=$(cf_curl -H "X-API-Key: $CATALOG_KEY" "$CATALOG/api/services?internal=true")
TOTAL=$(jq '.count' <<< "$SERVICES_JSON")
echo "got $TOTAL services"

CREATED=0; UPDATED=0; UNCHANGED=0; ERRORS=0

# Iterate service names
NAMES=$(jq -r '.services[].name' <<< "$SERVICES_JSON")
for name in $NAMES; do
  svc=$(jq -c --arg n "$name" '.services[] | select(.name == $n)' <<< "$SERVICES_JSON")
  newFM=$(build_frontmatter "$svc")
  filePath="$FOLDER/$name.md"
  encPath=$(urlenc "$filePath")

  # Try to read existing
  RESP=$(cf_curl -H "X-API-Key: $OBSIDIAN_KEY" -w "\n__HTTP__:%{http_code}" "$OBSIDIAN/api/files/$encPath")
  CODE=$(grep -oE '__HTTP__:[0-9]+$' <<< "$RESP" | cut -d: -f2)
  BODY=$(sed 's/__HTTP__:[0-9]*$//' <<< "$RESP")

  if [ "$CODE" = "200" ]; then
    # File exists — split on second `---`, keep the body
    EXISTING=$(jq -r '.content' <<< "$BODY")
    # Find the position after the second `---\n`. Use awk to track delimiter count.
    USER_BODY=$(awk 'BEGIN{c=0} /^---$/{c++; if(c==2){found=1; next}} found{print}' <<< "$EXISTING")
    NEW_FILE=$(printf '%s%s' "$newFM" "$(printf '\n%s' "$USER_BODY")")

    # Compare frontmatter only (strip dynamic last_synced for hash).
    norm_old=$(awk 'BEGIN{c=0; out=""} /^---$/{c++; if(c==2){print out; exit}} {if(!/^last_synced:/) out=out"\n"$0}' <<< "$EXISTING")
    norm_new=$(awk 'BEGIN{c=0; out=""} /^---$/{c++; if(c==2){print out; exit}} {if(!/^last_synced:/) out=out"\n"$0}' <<< "$newFM")

    if [ "$norm_old" = "$norm_new" ]; then
      UNCHANGED=$((UNCHANGED+1))
      continue
    fi

    PAYLOAD=$(jq -n --arg c "$NEW_FILE" '{content: $c}')
    R=$(cf_curl -X PUT -H "X-API-Key: $OBSIDIAN_KEY" -H "Content-Type: application/json" \
      -d "$PAYLOAD" -w "%{http_code}" -o /dev/null "$OBSIDIAN/api/files/$encPath")
    if [ "$R" = "201" ] || [ "$R" = "200" ]; then
      UPDATED=$((UPDATED+1))
    else
      echo "ERROR updating $name: HTTP $R"
      ERRORS=$((ERRORS+1))
    fi

  elif [ "$CODE" = "404" ]; then
    # New file — write frontmatter + stub body
    STUB=$(build_stub_body "$svc")
    NEW_FILE="${newFM}${STUB}"
    PAYLOAD=$(jq -n --arg c "$NEW_FILE" '{content: $c}')
    R=$(cf_curl -X PUT -H "X-API-Key: $OBSIDIAN_KEY" -H "Content-Type: application/json" \
      -d "$PAYLOAD" -w "%{http_code}" -o /dev/null "$OBSIDIAN/api/files/$encPath")
    if [ "$R" = "201" ]; then
      CREATED=$((CREATED+1))
    else
      echo "ERROR creating $name: HTTP $R"
      ERRORS=$((ERRORS+1))
    fi
  else
    echo "ERROR reading $name: HTTP $CODE"
    ERRORS=$((ERRORS+1))
  fi
done

echo ""
echo "summary: created=$CREATED updated=$UPDATED unchanged=$UNCHANGED errors=$ERRORS total=$TOTAL"
